### PR TITLE
Added console.table and prettify the code. 

### PR DESCRIPTION
**Pull request by luqmanrom**

### CODE REVIEW

**Comment by luqmanrom** [comment]
screen shot 2015-03-04 at 1 07 55 pm

**Comment by bahmutov** [comment]
Hi, it would be very cool, but could you make sure the tests pass first? I would be happy to merge your feature after that

**Comment by luqmanrom** [comment]
What are reasons the Travis CI failed?

**Comment by bahmutov** [comment]
Look at the details for the failed build - https://travis-ci.org/bahmutov/console-log-div/jobs/53087785

Have you tried running "grunt" command locally?

```
Running "jshint:all" (jshint) task
console-log-div.js
------------------
 W097  Line 1, Col 1     Use the function form of "use strict".     
 W122  Line 94, Col 30   Invalid typeof value 'Undefined'           
 W109  Line 100, Col 41  Strings must use singlequote.              
 W109  Line 101, Col 40  Strings must use singlequote.              
 W109  Line 102, Col 35  Strings must use singlequote.              
 W109  Line 102, Col 49  Strings must use singlequote.              
 W109  Line 106, Col 37  Strings must use singlequote.              
 W004  Line 111, Col 20  'i' is already defined.                    
 W109  Line 112, Col 38  Strings must use singlequote.              
 W109  Line 113, Col 39  Strings must use singlequote.              
 W109  Line 116, Col 43  Strings must use singlequote.              
 W071  Line 88, Col 38   This function has too many statements. (22)
 W033  Line 122, Col 6   Missing semicolon.                         
 W117  Line 100, Col 22  '$' is not defined.                        
 W117  Line 101, Col 21  '$' is not defined.                        
 W117  Line 102, Col 22  '$' is not defined.                        
 W117  Line 106, Col 24  '$' is not defined.                        
 W117  Line 112, Col 25  '$' is not defined.                        
 W117  Line 113, Col 26  '$' is not defined.                        
 W117  Line 116, Col 30  '$' is not defined.                        
× 20 problems in 1 file
Warning: Task "jshint:all" failed. Use --force to continue.
Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
The command "npm test" exited with 1.
```

**Comment by luqmanrom** [comment]
I tried. But I had few errors. 

module.js:340
    throw err;
          ^
Error: Cannot find module './lexer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/macair/Vagrant/my-project/console-log-div/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/coffee-script.js:10:10)
    at Object.<anonymous> (/Users/macair/Vagrant/my-project/console-log-div/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/coffee-script.js:167:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by bahmutov** [comment]
Looks like you are fixing the lint errors, but there is a huge obstacle - you used jQuery to create the table - I think this is bad idea. The original code had no dependencies - adding jQuery is too much for this simple task. Can you use plain javascript dom api to add table rows, please? http://youmightnotneedjquery.com/ is a good resource, but in this case you might just concatenate html and use something like innerHTML to add it to the DOM

**Comment by luqmanrom** [comment]
I finally get the grunt works and fixed the errors.

**Comment by luqmanrom** [comment]
Are you merging this?

**Comment by bahmutov** [comment]
Sorry about the delay, slipped my attention. published as 0.6.0

**Pull request merged**
